<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="Hotcakes.Commerce">
      <HintPath>\\Mac\Home\Downloads\DevSamples\References\Hotcakes.Commerce.dll</HintPath>
    </Reference>
    <Reference Include="Hotcakes.Commerce.Dnn">
      <HintPath>\\Mac\Home\Downloads\DevSamples\References\Hotcakes.Commerce.Dnn.dll</HintPath>
    </Reference>
    <Reference Include="Hotcakes.CommerceDTO">
      <HintPath>\\Mac\Home\Downloads\DevSamples\References\Hotcakes.CommerceDTO.dll</HintPath>
    </Reference>
    <Reference Include="Hotcakes.Modules">
      <HintPath>\\Mac\Home\Downloads\DevSamples\References\Hotcakes.Modules.dll</HintPath>
    </Reference>
    <Reference Include="Hotcakes.Payment">
      <HintPath>\\Mac\Home\Downloads\DevSamples\References\Hotcakes.Payment.dll</HintPath>
    </Reference>
    <Reference Include="Hotcakes.Web">
      <HintPath>\\Mac\Home\Downloads\DevSamples\References\Hotcakes.Web.dll</HintPath>
    </Reference>
    <Reference Include="Newtonsoft.Json">
      <HintPath>\\Mac\Home\Downloads\DevSamples\References\Newtonsoft.Json.dll</HintPath>
    </Reference>
    <Reference Include="System.Web.Helpers">
      <HintPath>\\Mac\Home\Downloads\DevSamples\References\System.Web.Helpers.dll</HintPath>
    </Reference>
    <Reference Include="System.Web.Mvc">
      <HintPath>\\Mac\Home\Downloads\DevSamples\References\System.Web.Mvc.dll</HintPath>
    </Reference>
    <Reference Include="System.Web.Razor">
      <HintPath>\\Mac\Home\Downloads\DevSamples\References\System.Web.Razor.dll</HintPath>
    </Reference>
    <Reference Include="System.Web.WebPages">
      <HintPath>\\Mac\Home\Downloads\DevSamples\References\System.Web.WebPages.dll</HintPath>
    </Reference>
    <Reference Include="System.Web.WebPages.Deployment">
      <HintPath>\\Mac\Home\Downloads\DevSamples\References\System.Web.WebPages.Deployment.dll</HintPath>
    </Reference>
    <Reference Include="System.Web.WebPages.Razor">
      <HintPath>\\Mac\Home\Downloads\DevSamples\References\System.Web.WebPages.Razor.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
